name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Run formatting
        run: deno fmt --check

      - name: Linting
        run: deno lint

      - name: Testing
        run: deno test